// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[dino].tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Dino.tsx";
import * as $$1 from "./islands/Search.tsx";

const manifest = {
  routes: {
    "./routes/[dino].tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Dino.tsx": $$0,
    "./islands/Search.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
